# Pipeline to create a new version of the SAML Flask container and
# push it to DockerHub

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerId: emcconne 
  imageName: saml-flask

steps:
- script: |
    docker build -t $(dockerId)/$(imageName) .
    docker login -u $(dockerId) -p $(pswd)
    docker push $(dockerId)/$(imageName)
  env:
    pswd: $(dockerPassword)   