# Pipeline to create a new version of the SAML Flask container and
# push it to DockerHub 

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: Docker
  - name: dockerId
    value: emcconne
  - name: imageName
    value: saml-flask

steps:
# Checkout is done automatically but here for readability
- checkout: self

# Why was this build executed
- bash: |
    case $BUILD_REASON in
            "Manual") echo "$BUILD_REQUESTEDFOR manually queued the build." ;;
            "IndividualCI") echo "This is a CI build for $BUILD_REQUESTEDFOR." ;;
            "BatchedCI") echo "This is a batched CI build for $BUILD_REQUESTEDFOR." ;;
        *) $BUILD_REASON ;;
    esac
  condition: eq( variables['Agent.OS'], 'Linux' )
  displayName: Get Build Reason

# Build and Push container to DockerHub
- script: |
    GIT_COMMIT=$( git rev-parse --short HEAD )
    echo '##vso[task.setvariable variable=GITCOMMIT]$GIT_COMMIT'
    VERSION=$( cat VERSION )
    echo '##vso[task.setvariable variable=VER]$(( cat VERSION ))'
    echo "GIT_COMMIT: $GIT_COMMIT"
    echo "GIT_COMMIT: $GITCOMMIT"
    echo "VERSION=$VERSION"
    echo "VERSION=$VER"
  displayName: Set Dynamic Pipeline Variables

- script: |
    echo "Next Script: GIT_COMMIT: $GIT_COMMIT"
    echo "Next Script: VERSION=$(version)"
    docker build -t $(dockerId)/$(imageName):$GIT_COMMIT -t $(dockerId)/$(imageName):latest -t $(dockerId)/$(imageName):$VERSION .
    docker login -u $(dockerId) -p $DOCKER_PASSWORD
    docker push $(dockerId)/$(imageName):$GIT_COMMIT
    docker push $(dockerId)/$(imageName):latest
    docker push $(dockerId)/$(imageName):$VERSION
  displayName: Build Docker Container
  env:
    DOCKER_PASSWORD: $(password)

# Azure CLI
# Publish container to ACI
- task: AzureCLI@1
  inputs:
    azureSubscription: python-saml-app
    scriptLocation: inlineScript
    inlineScript: |
      echo "Running az script."
      az container create -n saml-flask -g python-saml-app --image emcconne/saml-flask:$(gitCommit) --ports 5000 --dns-name-label saml-flask 
  displayName: Publish new container