# Pipeline to create a new version of the SAML Flask container and
# push it to DockerHub 

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: Docker
  - name: dockerId
    value: emcconne
  - name: imageName
    value: saml-flask

steps:
- bash: |
    case $BUILD_REASON in
            "Manual") echo "$BUILD_REQUESTEDFOR manually queued the build." ;;
            "IndividualCI") echo "This is a CI build for $BUILD_REQUESTEDFOR." ;;
            "BatchedCI") echo "This is a batched CI build for $BUILD_REQUESTEDFOR." ;;
        *) $BUILD_REASON ;;
    esac
  condition: eq( variables['Agent.OS'], 'Linux' )
  displayName: Get Buid Reason
  
- script: |
    GIT_COMMIT=$( git rev-parse --short HEAD )
    VERSION=$( cat VERSION )
    echo "dockerId=$(dockerId)"
    echo "imageName=$(imageName)"
    echo "Docker password=$(docker_pass)"
    echo "Docker username=$(docker_user)"
    echo "Build.BuildNumber=$(Build.BuildNumber)"
    echo "GIT_COMMIT: $GIT_COMMIT"
    echo "VERSION=$VERSION"
    echo "Docker password from env=$DOCKER_PASSWORD"
    docker build -t $(dockerId)/$(imageName):$GIT_COMMIT -t $(dockerId)/$(imageName):latest -t $(dockerId)/$(imageName):$VERSION .
    docker login -u $(dockerId) -p $DOCKER_PASSWORD
    docker push $(dockerId)/$(imageName):$GIT_COMMIT
    docker push $(dockerId)/$(imageName):latest
    docker push $(dockerId)/$(imageName):$VERSION
    az --version
  displayName: Build Docker Container
  env:
    DOCKER_PASSWORD: $(password)
